eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9002
spring:
  boot:
    admin:
      client:
        enabled: '@spring.boot.admin.enable@'
        url: http://localhost:9002
  zipkin:
    base-url: http://localhost:9091
    enabled: '@zipkin.enable@'
