eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: @eureka.port@
spring:
  boot:
    admin:
      client:
        enabled: '@spring.boot.admin.enable@'
        url: @spring.boot.admin.address@
  zipkin:
    base-url: @zipkin.address@
    enabled: '@zipkin.enable@'
sw_agent_name: ${spring.application.name}